// src/components/react/callApi/App.jsx
import { useState, useEffect } from 'react'
import {MyButton} from '../../wc/lit/my-button';


const url = "https://jsonplaceholder.typicode.com/users/";

export function App() {
  const [usersData, setUsersData] = useState([]);

  const getUsersData = async () => {
    const response = await fetch(url);
    const jsonData = await response.json();
    
    setUsersData([...jsonData]);
  };
  
 return (
    <div className="App" style={{display:'flex'}}>
      <div style={{flexGrow:1}}>
        <h2>
          React component + webcomponent button 
        </h2>

          {usersData.map(user => (
            <UserDetail user={user} key={user.id}/>
          )) }
      </div>
      <div>
        <my-button 
          text="load users" 
          onClick={e => getUsersData()}
          ></my-button>
      </div>
    </div>
  );
}


const UserDetail = ({user}) =>{
    return(
        <ul>
           <li>
              <strong>Name:</strong> {user.name}
            </li>
            <li>
              <strong>Website:</strong> {user.website}
            </li>
            <li>
              <strong>Email:</strong> {user.email}
            </li>
            <li>
              <strong>Phone:</strong> {user.phone}
            </li>
            <hr></hr>
        </ul>
    )
}

// src/components/vue/CallApi/App.vue
<script setup>
import {reactive, onMounted} from 'vue'
import {MyButton} from '../../wc/lit/my-button.js';


const state = reactive({
  users : []
})

const url = "https://jsonplaceholder.typicode.com/users/";

const loadUsers = async () => {
  if(state.users.length === 0){
    const response = await fetch(url);
    const jsonData = await response.json();
    state.users = [...jsonData]
  } 
}
</script>

<template>
  <div class="app">
      <div class="content">
        <h2>
          Vue component + webcomponent button 
        </h2>
        <ul>
          <li v-for="user in state.users" :key="user.id">
            <span>{{ user.name }}</span>
            -
            <span>{{ user.website }}</span>
            <hr>
          </li>
        </ul> 
      </div>
      <div class="aside">
        <my-button 
          text="load users" 
          @click="loadUsers"
        >
        </my-button>
      </div>
    </div>
</template>

<style scoped>
.app{
  display: flex;
}
.content{
  flex-grow: 1;
  padding: 1em;
}
.aside{
  margin-left: 1em;
}
span{
  padding: .5em;
}

</style>
