// src/components/svelte/tasks/Form.svelte
<script>
    import { onMount } from 'svelte';
    import { 
        postTaskItem, 
        itemSelected,
        initTaskItems 
    } from '../../../logics/tasks/taskStore';
    import FormTextInput from './FormTextInput.svelte';
    export let tasks

    const handleSubmit = async (e) => {
        try {
            await postTaskItem(itemSelected.value)
            itemSelected.set({ task: "" })
            // ssr & uze da platform
            window.location.reload()
        } catch (error) {
            console.log(error);
        }
    }
    onMount(()=>{
        initTaskItems(tasks)
    })
</script>
<form 
    on:submit|preventDefault={handleSubmit} 
    class="flex w-full items-center h-10 mb-5"
>
    <FormTextInput/>
    <button 
        type="submit" 
        class="text-xl font-bold cursor-pointer w-24 bg-slate-600 text-white rounded-tr rounded-br border-solid border-2 border-slate-900" 
        style="height: inherit"
    >
        {$itemSelected._id ? "Update" : "Add"}
    </button>
</form>

// src/components/react/tasks/Form.jsx
const Form = ({task, styles, addTask, handleChange }) => {
    return (
        <form 
            onSubmit={(e)=>{
                e.preventDefault()
                addTask(task)
            }} 
            className={'flex w-full items-center h-10 mb-5'}
        >
            <input
                className={'pl-2 grow outline-0 rounded-tl rounded-bl border-solid border-2 border-slate-800 text-slate-800'}
                style={{height: 'inherit'}}
                type="text"
                placeholder="Task to be done..."
                onChange={handleChange}
                value={task.task}
            />
            <button 
                type="submit" 
                className={'text-xl font-bold cursor-pointer w-24 bg-slate-600 text-white rounded-tr rounded-br border-solid border-2 border-slate-900'} 
                style={{height: 'inherit'}}
            >
                {task._id ? "Update" : "Add"}
            </button>
        </form>
    )
}

export default Form
